/*
 * This file is generated by jOOQ.
 */
package org.plutusdev.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Links implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer        id;
    private final String         link;
    private final String         description;
    private final Short          status;
    private final Integer        createdBy;
    private final OffsetDateTime createdOn;
    private final Integer        updatedBy;
    private final OffsetDateTime updatedOn;

    public Links(Links value) {
        this.id = value.id;
        this.link = value.link;
        this.description = value.description;
        this.status = value.status;
        this.createdBy = value.createdBy;
        this.createdOn = value.createdOn;
        this.updatedBy = value.updatedBy;
        this.updatedOn = value.updatedOn;
    }

    public Links(
        Integer        id,
        String         link,
        String         description,
        Short          status,
        Integer        createdBy,
        OffsetDateTime createdOn,
        Integer        updatedBy,
        OffsetDateTime updatedOn
    ) {
        this.id = id;
        this.link = link;
        this.description = description;
        this.status = status;
        this.createdBy = createdBy;
        this.createdOn = createdOn;
        this.updatedBy = updatedBy;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>bootcamp.links.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>bootcamp.links.link</code>.
     */
    public String getLink() {
        return this.link;
    }

    /**
     * Getter for <code>bootcamp.links.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>bootcamp.links.status</code>.
     */
    public Short getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>bootcamp.links.created_by</code>.
     */
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Getter for <code>bootcamp.links.created_on</code>.
     */
    public OffsetDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Getter for <code>bootcamp.links.updated_by</code>.
     */
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Getter for <code>bootcamp.links.updated_on</code>.
     */
    public OffsetDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Links (");

        sb.append(id);
        sb.append(", ").append(link);
        sb.append(", ").append(description);
        sb.append(", ").append(status);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
