/*
 * This file is generated by jOOQ.
 */
package org.plutusdev.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.plutusdev.jooq.tables.Links;
import org.plutusdev.jooq.tables.Users;
import org.plutusdev.jooq.tables.records.LinksRecord;
import org.plutusdev.jooq.tables.records.UsersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * bootcamp.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LinksRecord> LINKS_PKEY = Internal.createUniqueKey(Links.LINKS, DSL.name("links_pkey"), new TableField[] { Links.LINKS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinksRecord, UsersRecord> LINKS__FK_LINK_CREATED_BY = Internal.createForeignKey(Links.LINKS, DSL.name("fk_link_created_by"), new TableField[] { Links.LINKS.CREATED_BY }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<LinksRecord, UsersRecord> LINKS__FK_LINK_UPDATED_BY = Internal.createForeignKey(Links.LINKS, DSL.name("fk_link_updated_by"), new TableField[] { Links.LINKS.UPDATED_BY }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
}
