/*
 * This file is generated by jOOQ.
 */
package org.plutusdev.jooq;


import org.plutusdev.jooq.tables.Links;
import org.plutusdev.jooq.tables.Users;


/**
 * Convenience access to all tables in bootcamp.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>bootcamp.links</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>bootcamp.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
