/*
 * This file is generated by jOOQ.
 */
package org.plutusdev.jooq.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.plutusdev.jooq.tables.Links;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinksRecord extends UpdatableRecordImpl<LinksRecord> implements Record8<Integer, String, String, Short, Integer, OffsetDateTime, Integer, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bootcamp.links.id</code>.
     */
    public LinksRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>bootcamp.links.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bootcamp.links.link</code>.
     */
    public LinksRecord setLink(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>bootcamp.links.link</code>.
     */
    public String getLink() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bootcamp.links.description</code>.
     */
    public LinksRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>bootcamp.links.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bootcamp.links.status</code>.
     */
    public LinksRecord setStatus(Short value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>bootcamp.links.status</code>.
     */
    public Short getStatus() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>bootcamp.links.created_by</code>.
     */
    public LinksRecord setCreatedBy(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>bootcamp.links.created_by</code>.
     */
    public Integer getCreatedBy() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>bootcamp.links.created_on</code>.
     */
    public LinksRecord setCreatedOn(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>bootcamp.links.created_on</code>.
     */
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>bootcamp.links.updated_by</code>.
     */
    public LinksRecord setUpdatedBy(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>bootcamp.links.updated_by</code>.
     */
    public Integer getUpdatedBy() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>bootcamp.links.updated_on</code>.
     */
    public LinksRecord setUpdatedOn(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>bootcamp.links.updated_on</code>.
     */
    public OffsetDateTime getUpdatedOn() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, Short, Integer, OffsetDateTime, Integer, OffsetDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, Short, Integer, OffsetDateTime, Integer, OffsetDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Links.LINKS.ID;
    }

    @Override
    public Field<String> field2() {
        return Links.LINKS.LINK;
    }

    @Override
    public Field<String> field3() {
        return Links.LINKS.DESCRIPTION;
    }

    @Override
    public Field<Short> field4() {
        return Links.LINKS.STATUS;
    }

    @Override
    public Field<Integer> field5() {
        return Links.LINKS.CREATED_BY;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Links.LINKS.CREATED_ON;
    }

    @Override
    public Field<Integer> field7() {
        return Links.LINKS.UPDATED_BY;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return Links.LINKS.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLink();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Short component4() {
        return getStatus();
    }

    @Override
    public Integer component5() {
        return getCreatedBy();
    }

    @Override
    public OffsetDateTime component6() {
        return getCreatedOn();
    }

    @Override
    public Integer component7() {
        return getUpdatedBy();
    }

    @Override
    public OffsetDateTime component8() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLink();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Short value4() {
        return getStatus();
    }

    @Override
    public Integer value5() {
        return getCreatedBy();
    }

    @Override
    public OffsetDateTime value6() {
        return getCreatedOn();
    }

    @Override
    public Integer value7() {
        return getUpdatedBy();
    }

    @Override
    public OffsetDateTime value8() {
        return getUpdatedOn();
    }

    @Override
    public LinksRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LinksRecord value2(String value) {
        setLink(value);
        return this;
    }

    @Override
    public LinksRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public LinksRecord value4(Short value) {
        setStatus(value);
        return this;
    }

    @Override
    public LinksRecord value5(Integer value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public LinksRecord value6(OffsetDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public LinksRecord value7(Integer value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public LinksRecord value8(OffsetDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public LinksRecord values(Integer value1, String value2, String value3, Short value4, Integer value5, OffsetDateTime value6, Integer value7, OffsetDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinksRecord
     */
    public LinksRecord() {
        super(Links.LINKS);
    }

    /**
     * Create a detached, initialised LinksRecord
     */
    public LinksRecord(Integer id, String link, String description, Short status, Integer createdBy, OffsetDateTime createdOn, Integer updatedBy, OffsetDateTime updatedOn) {
        super(Links.LINKS);

        setId(id);
        setLink(link);
        setDescription(description);
        setStatus(status);
        setCreatedBy(createdBy);
        setCreatedOn(createdOn);
        setUpdatedBy(updatedBy);
        setUpdatedOn(updatedOn);
    }
}
